// models/Purchase.js
const mongoose = require('mongoose');

const purchaseSchema = new mongoose.Schema({
    // Purchase Key (Generated by admin, given to user)
    purchaseKey: {
        type: String,
        required: true,
        unique: true,
        index: true
    },
    
    // Status: pending (waiting for user), used (downloaded), expired
    status: {
        type: String,
        enum: ['pending', 'used', 'expired', 'cancelled'],
        default: 'pending'
    },
    
    // Relationships
    beat: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Beat',
        required: true
    },
    user: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: true
    },
    seller: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: true
    },
    
    // Financial info
    amount: {
        type: Number,
        required: true
    },
    currency: {
        type: String,
        default: 'KES'
    },
    
    // Timing
    expiresAt: {
        type: Date,
        required: true
    },
    usedAt: {
        type: Date,
        default: null
    },
    
    // Security
    downloadAttempts: {
        type: Number,
        default: 0,
        max: 1 // Only allow 1 download attempt
    },
    
    // Timestamps
    createdAt: {
        type: Date,
        default: Date.now
    },
    updatedAt: {
        type: Date,
        default: Date.now
    }
});

// Indexes
purchaseSchema.index({ user: 1, status: 1 });
purchaseSchema.index({ seller: 1 });
purchaseSchema.index({ purchaseKey: 1, user: 1 });
purchaseSchema.index({ expiresAt: 1 });

// Update timestamp on save
purchaseSchema.pre('save', function(next) {
    this.updatedAt = Date.now();
    
    // Auto-expire if past expiration
    if (this.expiresAt < new Date() && this.status === 'pending') {
        this.status = 'expired';
    }
    
    next();
});

// Virtual for checking if key is valid
purchaseSchema.virtual('isValid').get(function() {
    return this.status === 'pending' && this.expiresAt > new Date();
});

const Purchase = mongoose.model('Purchase', purchaseSchema);
module.exports = Purchase;